<?xml version="1.0" encoding="UTF-8" standalone="no"?><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>de.iip-ecosphere.platform</groupId>
  <artifactId>toolsDependencies</artifactId>
  <version>0.8.2-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>toolsDependencies with basic dependencies</name>
  <description>The managed dependencies for the common tools of the oktoflow platform.</description>
  <url>https://oktoflow.de/</url>

  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
    </license>
    <license>
      <name>Eclipse Public License, Version 1.0</name>
      <url>https://projects.eclipse.org/content/eclipse-public-license-1.0</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <developers>
    <developer>
      <id>eichelbe</id>
      <name>Holger Eichelberger</name>
      <email>eichelberger@sse.uni-hildesheim.de</email>
      <url>https://sse.uni-hildesheim.de/mitglieder/dr-holger-eichelberger/</url>
      <organization>SSE @ University of Hildesheim</organization>
      <organizationUrl>https://sse.uni-hildesheim.de/</organizationUrl>
      <roles>
        <role>architect</role>
        <role>developer</role>
      </roles>
      <timezone>Europe/Berlin</timezone>
    </developer>
    <developer>
      <id>JimmiAppel</id>
      <name>Alexander Weber</name>
      <email>weber@sse.uni-hildesheim.de</email>
      <url>https://sse.uni-hildesheim.de/</url>
      <organization>SSE @ University of Hildesheim</organization>
      <organizationUrl>https://sse.uni-hildesheim.de/</organizationUrl>
      <roles>
        <role>developer</role>
      </roles>
      <timezone>Europe/Berlin</timezone>
    </developer>
  </developers>

  <scm>
    <url>https://github.com/iip-ecosphere/platform.git</url>
  </scm>

  <repositories>       
    <repository>
      <id>SSE-mvn</id> <!-- same ID as in easy-maven-settings.xml -->
      <name>SSE</name>
      <url>https://projects.sse.uni-hildesheim.de/qm/maven/</url>
      <layout>default</layout>
    </repository>
  </repositories>

  <pluginRepositories>
     <pluginRepository>
       <id>SSE-plugins</id>
       <name>SSE</name>
       <url>https://projects.sse.uni-hildesheim.de/qm/maven/</url>
       <layout>default</layout>
     </pluginRepository>
  </pluginRepositories>

  <properties>
      <jacocoArgLine/>
      <surefireArgLine/>
      <surefireCiLine/>
      <surefireForkCount>1</surefireForkCount>
      <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

     <!-- If changed, check against forced JUnit provider -->
      <junit.version>4.12</junit.version>
  
      <org.apache.maven.deploy.version>3.1.1</org.apache.maven.deploy.version>
      <kr.motd.maven.os.version>1.6.2</kr.motd.maven.os.version>
      <org.apache.maven.compiler.version>3.16.0</org.apache.maven.compiler.version>
      <org.apache.maven.javadoc.version>3.2.0</org.apache.maven.javadoc.version>
      <org.apache.maven.jar.version>3.2.0</org.apache.maven.jar.version>
      <org.apache.maven.surefire.version>3.0.0-M3</org.apache.maven.surefire.version>
      <org.apache.maven.assembly.version>3.1.1</org.apache.maven.assembly.version>
      <org.jacoco.maven.jacoco.version>0.8.8</org.jacoco.maven.jacoco.version>
      <org.apache.maven.source.version>3.2.0</org.apache.maven.source.version>
      <org.xolstice.maven.protobuf.version>0.6.1</org.xolstice.maven.protobuf.version>
      <io.github.ascopes.protobuf.version>5.1.10</io.github.ascopes.protobuf.version>
      <org.apache.maven.dependency.version>3.11.0</org.apache.maven.dependency.version>
      <org.apache.maven.shade.version>2.3</org.apache.maven.shade.version>
      <org.apache.maven.clean.version>2.5</org.apache.maven.clean.version>
      <org.apache.maven.resources.version>3.3.1</org.apache.maven.resources.version>
      <org.apache.maven.antrun.version>3.1.0</org.apache.maven.antrun.version>
      <org.codehaus.mojo.exec-maven-plugin.version>3.0.0</org.codehaus.mojo.exec-maven-plugin.version>
      <org.codehaus.mojo.build-helper-maven-plugin.version>3.4.0</org.codehaus.mojo.build-helper-maven-plugin.version>
      <com.coderplus.maven.plugins.copy-rename-maven-plugin.version>1.0</com.coderplus.maven.plugins.copy-rename-maven-plugin.version>
      <eclipse.m2e.lifecycle.mapping>1.0.0</eclipse.m2e.lifecycle.mapping>
      
      <maven.build.cache.exclude.value.1>gen</maven.build.cache.exclude.value.1> <!-- all examples -->
      <maven.build.cache.exclude.value.2>tomcat.*</maven.build.cache.exclude.value.2> <!-- temporary test dir -->
      <maven.build.cache.exclude.value.3>work</maven.build.cache.exclude.value.3> <!-- temporary test dir -->
      <maven.build.cache.exclude.value.4>null</maven.build.cache.exclude.value.4> <!-- Docker cfg bug -->
    
      <maven.build.cache.enabled>false</maven.build.cache.enabled> <!--  fails on windows -->
      <surefireProcessTimeout>3600</surefireProcessTimeout>
  </properties>

  <dependencyManagement>
    <dependencies>
    
    </dependencies>
  </dependencyManagement>
  
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-deploy-plugin</artifactId>
        <version>${org.apache.maven.deploy.version}</version>
      </plugin>     
    </plugins>

    <extensions>
      <!-- Enabling the use of SSH -->
      <extension>
        <groupId>org.apache.maven.wagon</groupId>
         <artifactId>wagon-ssh-external</artifactId>
         <version>1.0-beta-6</version>
      </extension>       
    </extensions>
  </build>
  
  <distributionManagement>
    <repository>
      <id>sse-projects</id>
      <url>scpexe://projects.sse.uni-hildesheim.de/var/www/qm/maven/</url>
    </repository>
    <snapshotRepository>
      <id>sse-projects</id>
      <url>scpexe://projects.sse.uni-hildesheim.de/var/www/qm/maven/</url>
    </snapshotRepository>
  </distributionManagement>  
  
</project>