version: '3.7'
services:
  minio:
    image: minio/minio
    ports:
      - "8000:9000"
    volumes:
      - "./minio-data:/data"
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    command: server /data
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - ./mytb-data:/data
      - ./mytb-logs:/var/log/thingsboard
