AAS Santa_s_Sleigh
 ASSET santasSleigh INSTANCE
 SUBMODEL BOM (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/1/0/Submodel)
  PROPERTY ArcheType = OneDown (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/ArcheType/1/0)
  ENTITY SantaSleigh_EntryNode (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/EntryNode/1/0)
   RELATIONSHIP hasPart_01 (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/HasPart/1/0)
   RELATIONSHIP hasPart_02 (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/HasPart/1/0)
   RELATIONSHIP hasPart_03 (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/HasPart/1/0)
   RELATIONSHIP hasPart_04 (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/HasPart/1/0)
   RELATIONSHIP hasPart_05 (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/HasPart/1/0)
   RELATIONSHIP hasPart_06 (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/HasPart/1/0)
   RELATIONSHIP hasPart_07 (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/HasPart/1/0)
   RELATIONSHIP hasPart_08 (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/HasPart/1/0)
   RELATIONSHIP hasPart_09 (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/HasPart/1/0)
   RELATIONSHIP hasPart_10 (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/HasPart/1/0)
   RELATIONSHIP hasPart_11 (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/HasPart/1/0)
   ENTITY node_Blitzen (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/Node/1/0)
   ENTITY node_Comet (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/Node/1/0)
   ENTITY node_Cupid (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/Node/1/0)
   ENTITY node_Dancer (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/Node/1/0)
   ENTITY node_Dasher (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/Node/1/0)
   ENTITY node_Donner (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/Node/1/0)
   ENTITY node_Prancer (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/Node/1/0)
   ENTITY node_Rudolph (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/Node/1/0)
   ENTITY node_Sleigh (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/Node/1/0)
   ENTITY node_Vixen (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/Node/1/0)
   ENTITY node_santa (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/Node/1/0)
 SUBMODEL TechnicalData (semanticId: iri:http://admin-shell.io/ZVEI/TechnicalData/Submodel/1/1)
  SMC FurtherInformation (semanticId: iri:https://admin-shell.io/ZVEI/TechnicalData/FurtherInformation/1/1)
   PROPERTY ValidDate = 2023-12-24T23:59:59.000Z (semanticId: iri:https://admin-shell.io/ZVEI/TechnicalData/ValidDate/1/1)
  SMC GeneralInformation (semanticId: iri:https://admin-shell.io/ZVEI/TechnicalData/GeneralInformation/1/1)
   FILE ProductImage length 43
  SMC ProductClassifications
  SMC TechnicalProperties