AAS Santa_s_Sleigh
 ASSET santasSleigh INSTANCE
 SUBMODEL BOM (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/1/0/Submodel)
  PROPERTY ArcheType = OneDown (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/ArcheType/1/0)
  ENTITY SantaSleigh_EntryNode (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/EntryNode/1/0)
   RELATIONSHIP hasPart_01 (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/HasPart/1/0)
   RELATIONSHIP hasPart_02 (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/HasPart/1/0)
   RELATIONSHIP hasPart_03 (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/HasPart/1/0)
   RELATIONSHIP hasPart_04 (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/HasPart/1/0)
   RELATIONSHIP hasPart_05 (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/HasPart/1/0)
   RELATIONSHIP hasPart_06 (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/HasPart/1/0)
   RELATIONSHIP hasPart_07 (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/HasPart/1/0)
   RELATIONSHIP hasPart_08 (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/HasPart/1/0)
   RELATIONSHIP hasPart_09 (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/HasPart/1/0)
   RELATIONSHIP hasPart_10 (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/HasPart/1/0)
   RELATIONSHIP hasPart_11 (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/HasPart/1/0)
   ENTITY node_Blitzen (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/Node/1/0)
   ENTITY node_Comet (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/Node/1/0)
   ENTITY node_Cupid (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/Node/1/0)
   ENTITY node_Dancer (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/Node/1/0)
   ENTITY node_Dasher (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/Node/1/0)
   ENTITY node_Donner (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/Node/1/0)
   ENTITY node_Prancer (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/Node/1/0)
   ENTITY node_Rudolph (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/Node/1/0)
   ENTITY node_Sleigh (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/Node/1/0)
   ENTITY node_Vixen (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/Node/1/0)
   ENTITY node_santa (semanticId: iri:https://admin-shell.io/idta/HierarchicalStructures/Node/1/0)
 SUBMODEL TechnicalData (semanticId: iri:https://admin-shell.io/ZVEI/TechnicalData/Submodel/1/2)
  SMC FurtherInformation (semanticId: iri:https://admin-shell.io/ZVEI/TechnicalData/FurtherInformation/1/1)
   PROPERTY ValidDate = 2023-12-24T23:59:59.000Z (semanticId: iri:https://admin-shell.io/ZVEI/TechnicalData/ValidDate/1/1)
  SMC GeneralInformation (semanticId: iri:https://admin-shell.io/ZVEI/TechnicalData/GeneralInformation/1/1)
   PROPERTY ManufacturerArticleNumber = MSS-001 (semanticId: irdi:0173-1#02-AAO676#003)
   PROPERTY ManufacturerName = Christmas (semanticId: irdi:0173-1#02-AAO677#002)
   PROPERTY ManufacturerOrderCode = MSS-2023 (semanticId: irdi:0173-1#02-AAO227#002)
   MLP ManufacturerProductDesignation (semanticId: irdi:0173-1#02-AAW338#001)
   FILE ProductImage01 (semanticId: iri:https://admin-shell.io/ZVEI/TechnicalData/ProductImage/1/1) length 43
  SMC ProductClassifications (semanticId: iri:https://admin-shell.io/ZVEI/TechnicalData/ProductClassifications/1/1)
   SMC ProductClassificationItem01 (semanticId: iri:https://admin-shell.io/ZVEI/TechnicalData/ProductClassificationItem/1/1)
    PROPERTY ClassificationSystemVersion = 13 (semanticId: iri:https://admin-shell.io/ZVEI/TechnicalData/ClassificationSystemVersion/1/1)
    PROPERTY ProductClassId = 0173-1#01-AIZ481#021 (semanticId: iri:https://admin-shell.io/ZVEI/TechnicalData/ProductClassId/1/1)
    PROPERTY ProductClassificationSystem = ECLASS (semanticId: iri:https://admin-shell.io/ZVEI/TechnicalData/ProductClassificationSystem/1/1)
  SMC TechnicalProperties (semanticId: iri:https://admin-shell.io/ZVEI/TechnicalData/TechnicalProperties/1/1)