from json import JSONEncoder
import json
import sys
# Importing module from directory 'main'
import os
cwd = os.getcwd()
main_dir = cwd.replace('test', 'main')
sys.path.insert(0, main_dir)
from Serializer import Serializer

class GenericSerializer(Serializer):
    """JSON transport serializer for Rec1.
       Generated by: EASy-Producer."""

    def __init__(self, cls):
        self.cls = cls


    class Encoder(JSONEncoder):
        """JSON encoder class for Rec1.
        Generated by: EASy-Producer."""

        def default(self, o):
            """Provides access to the attributes in o.

            Parameters:
              - o -- the object to serialize
            Returns:
              dict
                the attributes
            """
            return o.__dict__

    def readFrom(self, data: bytes):
        """Turns bytes into an object.

        Parameters:
          - data -- the data bytes
        Returns:
          object
            the deserialized object
        """

        result = self.cls()
        result.setParameters(json.loads(data))
        #result.__dict__ = json.loads(data)
        return result

    def writeTo(self, source) -> bytes:
        """Turns an object into bytes.

        Parameters:
          - source -- the object
        Returns:
          bytes
            the serialized data bytes
        """
        json_obj = GenericSerializer.Encoder().encode(source)
        b = json_obj.encode("UTF-8")
        return b
