services = {} # service id to service
serializers = {} # symbolic type name to SerializerToString
types = {}   # python type to symbolic type name  
receivers = {}
senders = {}
asyncTransformers = {}
syncTransformers = {}
netMgtKeyAddresses = {}
typeSubst = {} # type name->creator mapping table