AAS DEXPIExample
 ASSET ci INSTANCE
 SUBMODEL DEXPI (semanticId: iri:https://admin-shell.io/idta/DEXPI/1/0/Submodel)
  SMC Model01 (semanticId: iri:https://admin-shell.io/idta/DEXPI/1/0/Model)
   SMC MappingDirectory (semanticId: iri:https://admin-shell.io/idta/DEXPI/1/0/MappingDirectory)
    SMC generic01 (semanticId: iri:https://admin-shell.io/idta/DEXPI/1/0/TagMapping)
     PROPERTY Class = PlateHeatExchanger (semanticId: iri:https://admin-shell.io/idta/DEXPI/1/0/Class)
     PROPERTY LocalId = PlateHeatExchanger-1 (semanticId: iri:https://admin-shell.io/idta/DEXPI/1/0/LocalId)
     PROPERTY TagName = H1007 (semanticId: iri:https://admin-shell.io/idta/DEXPI/1/0/TagName)
     RELATIONSHIP generic (semanticId: iri:https://admin-shell.io/idta/DEXPI/1/0/MappingRelationship)
   FILE ModelFile (semanticId: iri:https://admin-shell.io/idta/DEXPI/1/0/ModelFile) length 0
   SMC ModelMetadata (semanticId: iri:https://admin-shell.io/idta/DEXPI/1/0/Model)
    PROPERTY ApprovalDate = 2024/01/01 00:01:00 (semanticId: iri:http://sandbox.dexpi.org/rdl/ApprovalDateRepresentationAssignmentClass)
    MLP ApprovalDescription (semanticId: iri:https://sandbox.dexpi.org/rdl/ApprovalDescriptionAssignmentClass)
    PROPERTY ApproverName = A. P. Prover (semanticId: iri:http://sandbox.dexpi.org/rdl/ApproverNameAssignmentClass)
    PROPERTY ArchiveNumber = XY923-463 (semanticId: iri:http://sandbox.dexpi.org/rdl/ArchiveNumberAssignmentClass)
    PROPERTY CheckerName = C. Hecker (semanticId: iri:http://sandbox.dexpi.org/rdl/CheckerNameAssignmentClass)
    PROPERTY CreationDate = 2024/01/01 00:01:00 (semanticId: iri:http://sandbox.dexpi.org/rdl/CreationDateRepresentationAssignmentClass)
    PROPERTY CreatorName = A. Creator (semanticId: iri:http://sandbox.dexpi.org/rdl/CreatorNameAssignmentClass)
    PROPERTY DesignerName = D. E. Signer (semanticId: iri:http://sandbox.dexpi.org/rdl/DesignerNameAssignmentClass)
    PROPERTY DrawingNumber = 123/A93 (semanticId: iri:http://sandbox.dexpi.org/rdl/DrawingNumberAssignmentClass)
    MLP DrawingSubTitle (semanticId: iri:http://sandbox.dexpi.org/rdl/DrawingSubTitleAssignmentClass)
    PROPERTY LastModificationDate = 2024/01/01 00:01:00 (semanticId: iri:http://sandbox.dexpi.org/rdl/LastModificationDateRepresentationAssignmentClass)
   FILE ModelRepresentation (semanticId: iri:https://admin-shell.io/idta/DEXPI/1/0/ModelRepresentation) length 0
  SMC PlantMetadata (semanticId: iri:https://admin-shell.io/idta/DEXPI/1/0/PlantMetadata)
   PROPERTY DateOfManufacture = 2024/01/01 00:01:00 (semanticId: irdi:0173-1#02-AAR972#002)
   PROPERTY EndProductCASName01 = 7732-18-5 (semanticId: iri:https://admin-shell.io/idta/DEXPI/1/0/EndProductCASName)
   PROPERTY EndProductName01 = water (semanticId: iri:https://admin-shell.io/idta/DEXPI/1/0/EndProductName)
   PROPERTY EnterpriseIdentificationCode = oil-gas-inc (semanticId: iri:http://sandbox.dexpi.org/rdl/EnterpriseIdentificationCodeAssignmentClass)
   PROPERTY EnterpriseName = Oil & Gas, Inc. (semanticId: iri:http://sandbox.dexpi.org/rdl/EnterpriseNameAssignmentClass)
   REFERENCE EnterpriseReference -> true (semanticId: iri:https://admin-shell.io/idta/DEXPI/1/0/EnterpriseReference)
   PROPERTY IndustrialComplexIdentificationCode = I-Chain (semanticId: iri:http://sandbox.dexpi.org/rdl/IndustrialComplexIdentificationCodeAssignmentClass)
   PROPERTY IndustrialComplexName = Isophorone Chain (semanticId: iri:http://sandbox.dexpi.org/rdl/IndustrialComplexNameAssignmentClass)
   REFERENCE IndustrialComplexReference -> true (semanticId: iri:https://admin-shell.io/idta/DEXPI/1/0/IndustrialComplexReference)
   PROPERTY ManufacturerName = Plant Segment Vendor or EPC company name (semanticId: irdi:0173-1#02-AAO677#002)
   PROPERTY PlantSectionIdentificationCode = 10 (semanticId: iri:http://sandbox.dexpi.org/rdl/PlantSectionIdentificationCodeAssignmentClass)
   PROPERTY PlantSectionName = PlantSectionName (semanticId: iri:http://sandbox.dexpi.org/rdl/PlantSectionNameAssignmentClass)
   REFERENCE PlantSectionReference -> true (semanticId: iri:https://admin-shell.io/idta/DEXPI/1/0/PlantSectionReference)
   PROPERTY ProcessPlantIdentificationCode = ABC (semanticId: iri:http://sandbox.dexpi.org/rdl/ProcessPlantIdentificationCodeAssignmentClass)
   PROPERTY ProcessPlantName = ABC Plant (semanticId: iri:http://sandbox.dexpi.org/rdl/ProcessPlantNameAssignmentClass)
   REFERENCE ProcessPlantReference -> true (semanticId: iri:https://admin-shell.io/idta/DEXPI/1/0/ProcessPlantReference)
   PROPERTY ProjectName = a project (semanticId: iri:http://sandbox.dexpi.org/rdl/ProjectNameAssignmentClass)
   PROPERTY ProjectNumber = P3.1415 (semanticId: iri:http://sandbox.dexpi.org/rdl/ProjectNumberAssignmentClass)
   PROPERTY SiteIdentificationCode = DC (semanticId: iri:http://sandbox.dexpi.org/rdl/SiteIdentificationCodeAssignmentClass)
   PROPERTY SiteName = Dexpi City (semanticId: iri:http://sandbox.dexpi.org/rdl/SiteNameAssignmentClass)
   REFERENCE SiteReference -> true (semanticId: iri:https://admin-shell.io/idta/DEXPI/1/0/SiteReference)
   PROPERTY SubProjectName = a sub-project (semanticId: iri:http://sandbox.dexpi.org/rdl/SubProjectNameAssignmentClass)
   PROPERTY SubProjectNumber = P3.1415-SP2 (semanticId: iri:http://sandbox.dexpi.org/rdl/SubProjectNumberAssignmentClass)