AAS WorkstationWorkerMatchingDataExample
 ASSET ci INSTANCE
 SUBMODEL WorkstationWorkerMatchingData (semanticId: iri:https://admin-shell.io/idta/sm/workstationworkermatchingdata/1/0)
  SMC ErgonomicWorkstationProfile (semanticId: iri:https://admin-shell.io/idta/smc/ergonomicworkstationprofile/1/0)
   SML AllowedPersonalLimitations (semanticId: iri:https://admin-shell.io/idta/sml/allowedpersonallimitations/1/0)
    PROPERTY AllowedPersonalLimitationsRecord01 = -- SubmodelElementCollection (semanticId: iri:https://admin-shell.io/idta/smc/allowedpersonallimitationsrecord/1/0)
   PROPERTY MaxLiftingWeight = 16 (semanticId: iri:https://admin-shell.io/idta/prop/maxliftingweight/1/0)
   PROPERTY MinWorkerHeight = 170 (semanticId: iri:https://admin-shell.io/idta/prop/minworkerheight/1/0)
  SMC GeneralWorkstationData (semanticId: iri:https://admin-shell.io/idta/smc/generalworkstationdata/1/0)
   SML GeneralQualificationDemand (semanticId: iri:https://admin-shell.io/idta/sml/generalqualificationdemand/1/0)
    PROPERTY GeneralQualificationDemandRecord01 = -- SubmodelElementCollection (semanticId: iri:https://admin-shell.io/idta/smc/generalqualificationdemandrecord/1/0)
   SML GeneralSkillDemand (semanticId: iri:https://admin-shell.io/idta/sml/generalskilldemand/1/0)
    PROPERTY GeneralSkillDemandRecord01 = -- SubmodelElementCollection (semanticId: iri:https://admin-shell.io/idta/smc/generalskilldemandrecord/1/0)
   SMC WorkstationInformation (semanticId: iri:https://admin-shell.io/idta/smc/workstationinformation/1/0)
    MLP Directions (semanticId: iri:https://admin-shell.io/idta/mlp/directions/1/0)
    MLP LocationDescription (semanticId: iri:https://admin-shell.io/idta/mlp/locationdescription/1/0)
    MLP NecessaryPersonalTools (semanticId: iri:https://admin-https://admin-shell.io/idta/mlp/necessarypersonaltools/1/0)
    MLP OrgName (semanticId: iri:https://admin-shell.io/idta/mlp/orgname/1/0)
    MLP PersonalDataProcessing (semanticId: iri:https://admin-shell.io/idta/mlp/personaldataprocessing/1/0)
    MLP RequiredPersonalSafetyEquipment (semanticId: iri:https://admin-shell.io/idta/mlp/requiredpersonalsafetyequipment/1/0)
    MLP TypeOfWorkstation (semanticId: iri:https://admin-shell.io/idta/mlp/typeofworkstation/1/0)
    MLP WorkerAssistanceInformation (semanticId: iri:https://admin-shell.io/idta/mlp/workerassistanceeinformation/1/0)
    PROPERTY WorkstationId = mil0123 (semanticId: iri:https://admin-shell.io/idta/prop/workstationid/1/0)
    PROPERTY WorkstationName = milling machine (semanticId: iri:https://admin-shell.io/idta/prop/workstationname/1/0)
  SML PlannedQualificationDemand (semanticId: iri:https://admin-shell.io/idta/sml/plannedqualificationdemand/1/0)
   PROPERTY PlannedQualificationDemandRecord01 = -- SubmodelElementCollection (semanticId: iri:https://admin-shell.io/idta/smc/plannedqualificationdemandrecord/1/0)
  SML PlannedSkillDemand (semanticId: iri:https://admin-shell.io/idta/sml/plannedskilldemand/1/0)
   PROPERTY PlannedSkillDemandRecord01 = -- SubmodelElementCollection (semanticId: iri:https://admin-shell.io/idta/smc/plannedskilldemandrecord/1/0)
  SML WorkstationConfigurationRecords (semanticId: iri:https://admin-shell.io/idta/sml/workstationconfigurationrecords/1/0)
   PROPERTY WorkstationConfigurationRecord01 = -- SubmodelElementCollection (semanticId: iri:https://admin-shell.io/idta/smc/workstationconfigurationrecord/1/0)
