AAS SimulationModelsExample
 ASSET ci INSTANCE
 SUBMODEL SimulationModels (semanticId: iri:https://admin-shell.io/idta/SimulationModels/SimulationModels/1/0)
  SMC SimulationModel01 (semanticId: iri:https://admin-shell.io/idta/SimulationModels/SimulationModel/1/0)
   PROPERTY DefaultSimTime = 0.0 (semanticId: iri:https://admin-shell.io/idta/SimulationModels/DefaultSimTime/1/0)
   PROPERTY EngineeringDomain01 = TEST (semanticId: iri:https://admin-shell.io/idta/SimulationModels/EngineeringDomain/1/0)
   SMC Environment01 (semanticId: iri:https://admin-shell.io/idta/SimulationModels/Environment/1/0)
    MLP DependencyEnvironment (semanticId: iri:https://admin-shell.io/idta/SimulationModels/DependencyEnvironment/1/0)
    PROPERTY OperatingSystem = TEST (semanticId: iri:https://admin-shell.io/idta/SimulationModels/OperatingSystem/1/0)
    SMC SimulationTool01 (semanticId: iri:https://admin-shell.io/idta/SimulationModels/simulationTool/1/0)
     PROPERTY Compiler01 = TEST (semanticId: iri:https://admin-shell.io/idta/SimulationModels/compiler/1/0)
     PROPERTY DependencySimTool01 = TEST (semanticId: iri:https://admin-shell.io/idta/SimulationModels/DependencySimTool/1/0)
     PROPERTY SimToolName = TEST (semanticId: iri:https://admin-shell.io/idta/SimulationModels/SimToolName/1/0)
     SMC SolverAndTolerances (semanticId: iri:https://admin-shell.io/idta/SimulationModels/SolverAndTolerances/1/0)
      PROPERTY FixedStepSize = 0.0 (semanticId: iri:https://admin-shell.io/idta/SimulationModels/FixedStepSize/1/0)
      PROPERTY SolverIncluded = false (semanticId: iri:https://admin-shell.io/idta/SimulationModels/SolverIncluded/1/0)
      PROPERTY StepSizeControlNeeded = false (semanticId: iri:https://admin-shell.io/idta/SimulationModels/StepSizeControlNeeded/1/0)
      PROPERTY StiffSolverNeeded = false (semanticId: iri:https://admin-shell.io/idta/SimulationModels/StiffSolverNeeded/1/0)
      SMC TestedToolSolverAlgorithm01 (semanticId: iri:https://admin-shell.io/idta/SimulationModels/TestedToolSolverAlgorithm/1/0)
       PROPERTY SolverAlgorithm = TEST (semanticId: iri:https://admin-shell.io/idta/SimulationModels/SolverAlgorithm/1/0)
       PROPERTY Tolerance = 0.0 (semanticId: iri:https://admin-shell.io/idta/SimulationModels/tolerance/1/0)
       PROPERTY ToolSolverFurtherDescription = TEST (semanticId: iri:https://admin-shell.io/idta/SimulationModels/ToolSolverFurtherDescription/1/0)
    PROPERTY ToolEnvironment01 = TEST (semanticId: iri:https://admin-shell.io/idta/SimulationModels/ToolEnvironment/1/0)
    PROPERTY VisualizationInformation = TEST (semanticId: iri:https://admin-shell.io/idta/SimulationModels/VisualizationInformation/1/0)
   FILE InitStateFile (semanticId: iri:https://admin-shell.io/idta/SimulationModels/InitStateFile/1/0) length 0
   PROPERTY InitStateMethod = TEST (semanticId: iri:https://admin-shell.io/idta/SimulationModels/InitStateMethod/1/0)
   PROPERTY LicenseModel = TEST (semanticId: iri:https://admin-shell.io/idta/SimulationModels/LicenseModel/1/0)
   SMC ModelFile (semanticId: iri:https://admin-shell.io/idta/SimulationModels/ModelFile/1/0)
    PROPERTY ModelFileType = TEST (semanticId: iri:https://admin-shell.io/idta/SimulationModels/ModelFileType/1/0)
    SMC ModelFileVersion01 (semanticId: iri:https://admin-shell.io/idta/SimulationModels/ModelFileVersion/1/0)
     FILE DigitalFile (semanticId: iri:https://admin-shell.io/idta/SimulationModels/DigitalFile/1/0) length 0
     FILE ModelFileReleaseNotesFile (semanticId: iri:https://admin-shell.io/idta/SimulationModels/ModelFileReleaseNotesFile/1/0) length 0
     MLP ModelFileReleaseNotesTxt (semanticId: iri:https://admin-shell.io/idta/SimulationModels/ModelFileReleaseNotesTxt/1/0)
     FILE ModelPreviewImage (semanticId: iri:https://admin-shell.io/idta/SimulationModels/ModelPreviewImage/1/0) length 0
     PROPERTY ModelVersionId = TEST (semanticId: iri:https://admin-shell.io/idta/SimulationModels/ModelVersionId/1/0)
   FILE ParamFile (semanticId: iri:https://admin-shell.io/idta/SimulationModels/ParamFile/1/0) length 0
   PROPERTY ParamMethod = TEST (semanticId: iri:https://admin-shell.io/idta/SimulationModels/ParamMethod/1/0)
   SMC Ports (semanticId: iri:https://admin-shell.io/idta/SimulationModels/Ports/1/0)
    SMC BinaryConnector01 (semanticId: iri:https://admin-shell.io/idta/SimulationModels/BinaryConnector/1/0)
     PROPERTY BinaryConDescription = TEST (semanticId: iri:https://admin-shell.io/idta/SimulationModels/BinaryConDescription/1/0)
     PROPERTY BinaryConName = TEST (semanticId: iri:https://admin-shell.io/idta/SimulationModels/BinaryConnectorName/1/0)
    SMC PortsConnector01 (semanticId: iri:https://admin-shell.io/idta/SimulationModels/PortsConnector/1/0)
     MLP PortConDescription (semanticId: iri:https://admin-shell.io/idta/SimulationModels/PortConDescription/1/0)
     PROPERTY PortConnectorName = TEST (semanticId: iri:https://admin-shell.io/idta/SimulationModels/PortConnectorName/1/0)
     SMC Variable01 (semanticId: iri:https://admin-shell.io/idta/SimulationModels/Variable/1/0)
      PROPERTY Range = TEST (semanticId: iri:https://admin-shell.io/idta/SimulationModels/Range/1/0)
      MLP UnitDescription (semanticId: iri:https://admin-shell.io/idta/SimulationModels/UnitDescription/1/0)
      PROPERTY UnitList = TEST (semanticId: iri:https://admin-shell.io/idta/SimulationModels/UnitList/1/0)
      PROPERTY VariableCausality = TEST (semanticId: iri:https://admin-shell.io/idta/SimulationModels/VariableCausality/1/0)
      MLP VariableDescription (semanticId: iri:https://admin-shell.io/idta/SimulationModels/VariableDescription/1/0)
      PROPERTY VariableName = TEST (semanticId: iri:https://admin-shell.io/idta/SimulationModels/VariableName/1/0)
      PROPERTY VariablePrefix = TEST (semanticId: iri:https://admin-shell.io/idta/SimulationModels/VariablePrefix/1/0)
      PROPERTY VariableType = TEST (semanticId: iri:https://admin-shell.io/idta/SimulationModels/VariableType/1/0)
   FILE RefSimDocumentation01 (semanticId: iri:https://admin-shell.io/idta/SimulationModels/RefSimDocumentation/1/0) length 0
   PROPERTY ScopeOfModel01 = TEST (semanticId: iri:https://admin-shell.io/idta/SimulationModels/ScopeOfModel/1/0)
   SMC SimModManufacturerInformation01 (semanticId: iri:https://admin-shell.io/idta/SimulationModels/SimModManufacturerInformation/1/0)
    PROPERTY Company = TEST (semanticId: irdi:0173-1#02-AAW001#001)
    SMC Email (semanticId: irdi:0173-1#02-AAQ836#005)
     PROPERTY EmailAddress = email@muster-ag.de (semanticId: irdi:0173-1#02-AAO198#002)
     MLP PublicKey (semanticId: irdi:0173-1#02-AAO200#002)
     PROPERTY TypeOfEmailAddress = office (semanticId: irdi:0173-1#02-AAO199#003)
     MLP TypeOfPublicKey (semanticId: irdi:0173-1#02-AAO201#002)
    PROPERTY Language01 = TEST (semanticId: irdi:0173-1#02-AAO895#003)
    SMC Phone (semanticId: iri:https://admin-shell.io/zvei/nameplate/1/0/ContactInformations/ContactInformation/Phone)
     MLP AvailableTime (semanticId: iri:https://admin-shell.io/zvei/nameplate/1/0/ContactInformations/ContactInformation/AvailableTime/)
     MLP TelephoneNumber (semanticId: irdi:0173-1#02-AAO136#002)
     PROPERTY TypeOfTelephone = office (semanticId: irdi:0173-1#02-AAO137#003)
   SMC SimPurpose (semanticId: iri:https://admin-shell.io/idta/SimulationModels/SimPurpose/1/0)
    PROPERTY NegSimPurpose01 = TEST (semanticId: iri:https://admin-shell.io/idta/SimulationModels/NegSimPurpose/1/0)
    PROPERTY PosSimPurpose01 = TEST (semanticId: iri:https://admin-shell.io/idta/SimulationModels/PosSimPurpose/1/0)
   MLP Summary (semanticId: iri:https://admin-shell.io/idta/SimulationModels/Summary/1/0)
   PROPERTY TypeOfModel01 = TEST (semanticId: iri:https://admin-shell.io/idta/SimulationModels/TypeOfModel/1/0)