AAS TimeSeriesExample
 ASSET ci INSTANCE
 SUBMODEL TimeSeries (semanticId: iri:https://admin-shell.io/idta/TimeSeries/1/1)
  SMC Metadata (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Metadata/1/1)
   MLP Description (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Metadata/Description/1/1)
   MLP Name (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Metadata/Name/1/1)
   SMC Record (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Record/1/1)
    PROPERTY Time01 = TEST (semanticId: iri:https://oktoflow.de/semId-Time)
  SMC Segments (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segments/1/1)
   SMC ExternalSegment01 (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segments/ExternalSegment/1/1)
    BLOB Blob (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Blob/1/1) length 0
    MLP Description (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/Description/1/1)
    PROPERTY Duration = P3DT4H59M (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/Duration/1/1)
    PROPERTY EndTime = 2024/01/01 00:01:00 (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/EndTime/1/1)
    FILE File (semanticId: iri:https://admin-shell.io/idta/TimeSeries/File/1/1) length 0
    PROPERTY LastUpdate = 2024/01/01 00:01:00 (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/LastUpdate/1/1)
    MLP Name (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/Name/1/1)
    PROPERTY RecordCount = 13134 (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/RecordCount/1/1)
    PROPERTY SamplingInterval = 1 (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/SamplingInterval/1/1)
    PROPERTY SamplingRate = 3200 (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/SamplingRate/1/1)
    PROPERTY StartTime = 2024/01/01 00:01:00 (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/StartTime/1/1)
    PROPERTY State = completed (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/State/1/1)
   SMC InternalSegment01 (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segments/InternalSegment/1/1)
    MLP Description (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/Description/1/1)
    PROPERTY Duration = P3DT4H59M (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/Duration/1/1)
    PROPERTY EndTime = 2024/01/01 00:01:00 (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/EndTime/1/1)
    PROPERTY LastUpdate = 2024/01/01 00:01:00 (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/LastUpdate/1/1)
    MLP Name (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/Name/1/1)
    PROPERTY RecordCount = 13134 (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/RecordCount/1/1)
    SMC Records (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Records/1/1)
     SMC Record01 (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Record/1/1)
      PROPERTY Time01 = TEST (semanticId: iri:https://oktoflow.de/semId-Time)
    PROPERTY SamplingInterval = 1 (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/SamplingInterval/1/1)
    PROPERTY SamplingRate = 3200 (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/SamplingRate/1/1)
    PROPERTY StartTime = 2024/01/01 00:01:00 (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/StartTime/1/1)
    PROPERTY State = completed (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/State/1/1)
   SMC LinkedSegment01 (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segments/LinkedSegment/1/1)
    MLP Description (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/Description/1/1)
    PROPERTY Duration = P3DT4H59M (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/Duration/1/1)
    PROPERTY EndTime = 2024/01/01 00:01:00 (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/EndTime/1/1)
    PROPERTY Endpoint = TEST (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Endpoint/1/1)
    PROPERTY LastUpdate = 2024/01/01 00:01:00 (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/LastUpdate/1/1)
    MLP Name (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/Name/1/1)
    PROPERTY Query = TEST (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Query/1/1)
    PROPERTY RecordCount = 13134 (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/RecordCount/1/1)
    PROPERTY SamplingInterval = 1 (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/SamplingInterval/1/1)
    PROPERTY SamplingRate = 3200 (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/SamplingRate/1/1)
    PROPERTY StartTime = 2024/01/01 00:01:00 (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/StartTime/1/1)
    PROPERTY State = completed (semanticId: iri:https://admin-shell.io/idta/TimeSeries/Segment/State/1/1)