package iip.datatypes;

import com.fasterxml.jackson.annotation.JsonIgnore;

import de.iip_ecosphere.platform.support.ConfiguredName;

/**
 * Interface of the application data type RoutingCommand.
 * Generated by: EASy-Producer.
 */
@ConfiguredName("RoutingCommand")
public interface RoutingCommandOld {

    /**
     * Returns the value of {@code cmd}.
     *
     * @return the value
     */
    @JsonIgnore
    public String getCmd();

    /**
     * Changes the value of {@code cmd}.
     *
     * @param value the new value
     */
    @JsonIgnore
    public void setCmd(String value);

}
