package de.iip_ecosphere.platform.impl.shop;

import java.io.*;        
import de.iip_ecosphere.platform.services.environment.*;
import iip.datatypes.*;
import iip.impl.*;

/**
 * Service implementation for net node 'Sink'.
 * Generated by: EASy-Producer.
 */
public class TestSink extends SinkImpl {

    /**
    * Fallback constructor, also used for testing main program.
    */
    public TestSink() {
        super(ServiceKind.SINK_SERVICE);
    }

    /**
    * Creates a service instance from a service id and a YAML artifact.
    * 
    * @param serviceId the service id
    * @param ymlFile the YML file containing the YAML artifact with the service descriptor
    */
    public TestSink(String serviceId, InputStream ymlFile) {
        super(serviceId, ymlFile);
    }

    @Override
    public void processNewOutput(NewOutput data) {
        System.out.println("OUT: " + data.getResult());
    }
                
    
}
