AAS SoftwareNameplateExample
 ASSET ci INSTANCE
 SUBMODEL SoftwareNameplate (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0)
  SMC SoftwareNameplate_Instance (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplateInstance)
   SMC ConfigurationPaths (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplate/SoftwareNameplateInstance/ConfigurationPaths)
    SMC ConfigurationPath01 (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplate/SoftwareNameplateInstance/ConfigurationPath)
     PROPERTY ConfigurationType = initial configuration (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplate/SoftwareNameplateInstance/ConfigurationType)
     PROPERTY ConfigurationURI = file:/C:/Users/mw30/Documents/ZVEI/AKITinAutomation/20201013 (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplate/SoftwareNameplateInstance/ConfigurationURI)
   SMC ContactInformation (semanticId: iri:https://admin-shell.io/zvei/nameplate/1/0/ContactInformations/ContactInformation)
    MLP AcademicTitle (semanticId: irdi:0173-1#02-AAO209#003)
    PROPERTY AddressOfAdditionalLink = http://me.here.de (semanticId: irdi:0173-1#02-AAQ326#002)
    MLP CityTown (semanticId: irdi:0173-1#02-AAO132#002)
    MLP Company (semanticId: irdi:0173-1#02-AAW001#001)
    MLP Department (semanticId: irdi:0173-1#02-AAO127#003)
    SMC Email (semanticId: irdi:0173-1#02-AAQ836#005)
     PROPERTY EmailAddress = john@doe.com (semanticId: irdi:0173-1#02-AAO198#002)
     MLP PublicKey (semanticId: irdi:0173-1#02-AAO200#002)
     PROPERTY TypeOfEmailAddress = office (semanticId: irdi:0173-1#02-AAO199#003)
     MLP TypeOfPublicKey (semanticId: irdi:0173-1#02-AAO201#002)
    SMC Fax (semanticId: irdi:0173-1#02-AAQ834#005)
     MLP FaxNumber (semanticId: irdi:0173-1#02-AAO195#002)
     PROPERTY TypeOfFaxNumber = secretary (semanticId: irdi:0173-1#02-AAO196#003)
    MLP FirstName (semanticId: irdi:0173-1#02-AAO206#002)
    MLP FurtherDetailsOfContact (semanticId: irdi:0173-1#02-AAO210#002)
    SMC IPCommunication01 (semanticId: iri:https://admin-shell.io/zvei/nameplate/1/0/ContactInformations/ContactInformation/IPCommunication/)
     PROPERTY AddressOfAdditionalLink = http://comm.doe.com (semanticId: irdi:0173-1#02-AAQ326#002)
     MLP AvailableTime (semanticId: iri:https://admin-shell.io/zvei/nameplate/1/0/ContactInformations/ContactInformation/AvailableTime/)
     PROPERTY TypeOfCommunication = Skype4business (semanticId: iri:https://admin-shell.io/zvei/nameplate/1/0/ContactInformations/ContactInformation/IPCommunication/TypeOfCommunication)
    SMC IPCommunication02 (semanticId: iri:https://admin-shell.io/zvei/nameplate/1/0/ContactInformations/ContactInformation/IPCommunication/)
     PROPERTY AddressOfAdditionalLink = sip://comm.doe.com (semanticId: irdi:0173-1#02-AAQ326#002)
     MLP AvailableTime (semanticId: iri:https://admin-shell.io/zvei/nameplate/1/0/ContactInformations/ContactInformation/AvailableTime/)
     PROPERTY TypeOfCommunication = SIP phone (semanticId: iri:https://admin-shell.io/zvei/nameplate/1/0/ContactInformations/ContactInformation/IPCommunication/TypeOfCommunication)
    MLP MiddleNames (semanticId: irdi:0173-1#02-AAO207#002)
    MLP NameOfContact (semanticId: irdi:0173-1#02-AAO205#002)
    MLP NationalCode (semanticId: irdi:0173-1#02-AAO134#002)
    MLP POBox (semanticId: irdi:0173-1#02-AAO130#002)
    SMC Phone (semanticId: iri:https://admin-shell.io/zvei/nameplate/1/0/ContactInformations/ContactInformation/Phone)
     MLP AvailableTime (semanticId: iri:https://admin-shell.io/zvei/nameplate/1/0/ContactInformations/ContactInformation/AvailableTime/)
     MLP TelephoneNumber (semanticId: irdi:0173-1#02-AAO136#002)
     PROPERTY TypeOfTelephone = secretary (semanticId: irdi:0173-1#02-AAO137#003)
    PROPERTY RoleOfContactPerson = administrativ contact (semanticId: irdi:0173-1#02-AAO204#003)
    MLP Street (semanticId: irdi:0173-1#02-AAO128#002)
    PROPERTY TimeZone = -6:00 (semanticId: iri:https://admin-shell.io/zvei/nameplate/1/0/ContactInformations/ContactInformation/TimeZone)
    MLP Title (semanticId: irdi:0173-1#02-AAO208#003)
   PROPERTY InstallationDate = 2020/11/19 09:30:20 (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplate/SoftwareNameplateInstance/InstallationDate)
   PROPERTY InstallationPath = file:/C:/Windows/Program%20Files/Demo/Firmware (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplate/SoftwareNameplateInstance/InstallationPath)
   PROPERTY InstallationSource = https://tud.de/inf/pk/installation/firmware/src (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplate/SoftwareNameplateInstance/InstallationSource)
   SMC InstalledModules (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplate/SoftwareNameplateInstance/InstalledModules)
    PROPERTY InstalledModule01 = Module (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplate/SoftwareNameplateInstance/InstalledModule)
   PROPERTY InstalledOnArchitecture = x86-32 (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplate/SoftwareNameplateInstance/InstalledOnArchitecture)
   PROPERTY InstalledOnHost = IPC_42 (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplate/SoftwareNameplateInstance/InstalledOnHost)
   PROPERTY InstalledOnOS = Windows 10 (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplate/SoftwareNameplateInstance/InstalledOnOS)
   PROPERTY InstalledVersion = 0.9.1.0 (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplate/SoftwareNameplateInstance/InstalledVersion)
   PROPERTY InstanceName = My Software Instance (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplate/SoftwareNameplateInstance/InstanceName)
   PROPERTY SLAInformation = Service level GOLD USER (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplate/SoftwareNameplateInstance/SLAInformation)
   PROPERTY SerialNumber = 123456 (semanticId: irdi:0173-1#02-AAM556#002)
  SMC SoftwareNameplate_Type (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplateType)
   PROPERTY BuildDate = 2022/11/19 10:00:00 (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplate/SoftwareNameplateType/BuildDate)
   PROPERTY InstallationChecksum = 0x2783 (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplate/SoftwareNameplateType/InstallationChecksum)
   BLOB InstallationFile (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplate/SoftwareNameplateType/InstallationFile) length 0
   PROPERTY InstallationURI = https://tud.de/inf/pk/demos/download/DemoFirmware_09.zip (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplate/SoftwareNameplateType/InstallationURI)
   PROPERTY InstallerType = MSI (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplate/SoftwareNameplateType/InstallerType)
   MLP ManufacturerName (semanticId: irdi:0173-1#02-AAO677#002)
   MLP ManufacturerProductDescription (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplate/SoftwareNameplateType/ManufacturerProductDescription)
   MLP ManufacturerProductDesignation (semanticId: irdi:0173-1#02-AAW338#001)
   MLP ManufacturerProductFamily (semanticId: irdi:0173-1#02-AAU731#001)
   MLP ManufacturerProductType (semanticId: irdi:0173-1#02-AAO057#002)
   PROPERTY ReleaseDate = 2022/02/07 10:00:00 (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplate/SoftwareNameplateType/ReleaseDate)
   MLP ReleaseNotes (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplate/SoftwareNameplateType/ReleaseNotes)
   PROPERTY SoftwareType = PLC Runtime (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplate/SoftwareNameplateType/SoftwareType)
   PROPERTY URIOfTheProduct = ZVEI.I40.ITinAutomation.DemoSW_123456 (semanticId: irdi:0173-1#02-AAY811#001)
   PROPERTY Version = 0.9.1.0 (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplate/SoftwareNameplateType/Version)
   MLP VersionInfo (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplate/SoftwareNameplateType/VersionInfo)
   MLP VersionName (semanticId: iri:https://admin-shell.io/idta/SoftwareNameplate/1/0/SoftwareNameplate/SoftwareNameplateType/VersionName)