AAS WirelessCommunicationExample
 ASSET ci INSTANCE
 SUBMODEL WirelessCommunication (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/1/0)
  PROPERTY WirelessNetworkRole01 = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/WirelessNetworkRole/1/0)
  SMC Authentification01
  SMC Hardware01 (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/Hardware/1/0)
   PROPERTY AntennaHeight01 = 0.0 (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/Hardware/AntennaHeight/1/0)
   PROPERTY AntennaType01 = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/Hardware/AntennaType/1/0)
   PROPERTY ConnectorType01 = 0.0 (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/Hardware/ConnectorType/1/0)
   PROPERTY Interfaces01 = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/Hardware/Interface/1/0)
   PROPERTY NumberOfAntenas01 = 0 (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/Hardware/NumberOfAntennas/1/0)
  SMC License01 (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/1/0)
   SMC Applicant (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/Applicant/1/0)
    PROPERTY Address = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/Address/1/0)
    PROPERTY CompanyName = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/CompanyName/1/0)
    PROPERTY ContactFirstName = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/ContactFirstName/1/0)
    PROPERTY ContactSurname = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/ContactSurname/1/0)
    PROPERTY Description = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/Description/1/0)
    PROPERTY Fax = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/Fax/1/0)
    PROPERTY LicenseType = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/LicenseType/1/0)
    PROPERTY Mail = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/Mail/1/0)
    PROPERTY Phone = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/Phone/1/0)
   SMC FixedStation01 (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License//1/0)
    PROPERTY AltituteAntenna = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/FixedStation/AltituteAntenna/1/0)
    PROPERTY AltituteLocation = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/FixedStation/AltituteLocation/1/0)
    SMC GeographicPosition
    PROPERTY Location = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/FixedStation/Location/1/0)
    PROPERTY StationID = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/FixedStation/StationID/1/0)
   SMC FixedStation_2 (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/Allocation/1/0)
    SMC Conditions
    PROPERTY Status = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/Allocation/Status/1/0)
    PROPERTY TimeOfResponse = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/Allocation/TimeOfResponse/1/0)
    PROPERTY TimeofRequest = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/Allocation/TimeofRequest/1/0)
   SMC Frequency (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/Frequency/1/0)
    PROPERTY Frequencies = 0.0 (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/Frequencies/1/0)
    PROPERTY Frequency = 0.0 (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/Frequency/1/0)
    RANGE FrequencyRange (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/FrequencyRange/1/0) min 1 max 2
   SMC LicenseAcquisitionTechnicalData (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/LicenseAcquisitionTechnicalData/1/0)
    PROPERTY AccessMethod = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/LicenseAcquisitionTechnicalData/AccessMethod/1/0)
    PROPERTY AntennaGain = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/LicenseAcquisitionTechnicalData/AntennaGain/1/0)
    PROPERTY Azimuth = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/LicenseAcquisitionTechnicalData/Azimuth/1/0)
    PROPERTY Bandwidth = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/LicenseAcquisitionTechnicalData/Bandwidth/1/0)
    PROPERTY DuplexMethod = FDD, TDD (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/LicenseAcquisitionTechnicalData/DuplexMethod/1/0)
    PROPERTY Elevation = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/LicenseAcquisitionTechnicalData/Elevation/1/0)
    PROPERTY EquipmentMarketing = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/LicenseAcquisitionTechnicalData/EquipmentMarketing/1/0)
    PROPERTY Interfaces = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/LicenseAcquisitionTechnicalData/Interfaces/1/0)
    PROPERTY Manufacturer = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/LicenseAcquisitionTechnicalData/Manufacturer/1/0)
    PROPERTY Polarisation = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/LicenseAcquisitionTechnicalData/Polarisation/1/0)
    PROPERTY TransmitterOutputPower = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/LicenseAcquisitionTechnicalData/TransmitterOutputPower/1/0)
    PROPERTY TypeOfModulation = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/LicenseAcquisitionTechnicalData/TypeOfModulation/1/0)
   SMC MobileStation01 (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/MobileStation/1/0)
    PROPERTY KindOfOperation = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/MobileStation/KindOfOperation/1/0)
    PROPERTY Region = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/MobileStation/Region/1/0)
    PROPERTY StationID = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/MobileStation/StationID/1/0)
   SMC Operation (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/Operation/1/0)
    PROPERTY Day = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/Operation/Day/1/0)
    PROPERTY Duration = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/Operation/Duration/1/0)
    PROPERTY Month = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/Operation/Month/1/0)
    PROPERTY Year = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/License/Operation/Year/1/0)
  SMC OutputPower01 (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/ReceptionQuality/OutputPower/1/0)
   PROPERTY CurrentValue = 85.0 (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/OutputPower/CurrentValue/1/0)
   PROPERTY ParameterType = EIRP (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/OutputPower/ParameterType/1/0)
   RANGE Range (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/OutputPower/Range/1/0) min 0 max 125
   PROPERTY ReferenceValue = 85.0 (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/OutputPower/ReferenceValue/1/0)
   PROPERTY SpecifiedValue = 85.0 (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/OutputPower/SpecifiedValue/1/0)
  SMC RadioFrequency (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/RadioFrequency/1/0)
   SMC FrequencyBand (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/RadioFrequency/FrequencyBand/1/0)
    PROPERTY BandIDCurrent = [n78] (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/RadioFrequency/FrequencyBand/BandIDCurrent/1/0)
    PROPERTY BandIDList01 = [n78, n43] (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/RadioFrequency/FrequencyBand/BandIDList/1/0)
    PROPERTY Bandwidth = 100.0 (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/RadioFrequency/FrequencyBand/Bandwidth/1/0)
    PROPERTY CenterFrequecy = 3700.0 (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/RadioFrequency/FrequencyBand/CenterFrequecy/1/0)
   SMC RadioFrequencyChannel (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/RadioFrequency/RadioFrequencyChannel/1/0)
    PROPERTY ChannelNumbering01 = 14 (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/RadioFrequency/RadioFrequencyChannel/ChannelNumbering/1/0)
    PROPERTY UsedChannelBandwidth = 0 (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/RadioFrequency/RadioFrequencyChannel/UsedChannelBandwidth/1/0)
    PROPERTY UsedChannelCentreFrequency = 0.0 (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/RadioFrequency/RadioFrequencyChannel/UsedChannelCentreFrequency/1/0)
  SMC ReceptionQuality01
  SMC WirelessCommunicationFunction (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/WirelessCommunicationFunction/1/0)
   PROPERTY CommunicationCycle01 = 0 (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/WirelessCommunicationFunction/CommunicationCycle/1/0)
   SMC MediumAccess01 (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/WirelessCommunicationFunction/MediumAccess/1/0)
    PROPERTY MediumAccessType = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/WirelessCommunicationFunction/MediumAccess/MediumAccessType/1/0)
    SMC SlotConfiguration (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/WirelessCommunicationFunction/MediumAccess/SlotConfiguration/1/0)
     PROPERTY NumberOfDownlinkSlots = 0 (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/WirelessCommunicationFunction/MediumAccess/SlotConfiguration/NumberOfDownlinkSlots/1/0)
     PROPERTY NumberOfSharedSlots = 0 (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/WirelessCommunicationFunction/MediumAccess/SlotConfiguration/NumberOfSharedSlots/1/0)
     PROPERTY NumberOfUpllinkSlots = 0 (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/WirelessCommunicationFunction/MediumAccess/SlotConfiguration/NumberOfUpllinkSlots/1/0)
   PROPERTY SecurityMechanism01 = TEST (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/WirelessCommunicationFunction/SecurityMechanism/1/0)
   PROPERTY TechnologyStandard = 5G NR (semanticId: iri:https://admin-shell.io/idta/WirelessCommunication/WirelessCommunicationFunction/TechnologyStandard/1/0)
