
[program:platform]
priority=800
directory=/opt/user/platform/gen
command=bash /opt/user/platform/gen/brokerPl_starter.sh

[program:ecs]
priority=801
directory=/opt/user/platform/gen
command=bash /opt/user/platform/gen/ecs_starter.sh

[program:serviceMgr]
priority=802
directory=/opt/user/platform/gen
command=bash /opt/user/platform/gen/serviceMgr_starter.sh

[program:monitoring]
priority=803
directory=/opt/user/platform/gen
command=bash /opt/user/platform/gen/monitoring_starter.sh

[program:ui]
priority=804
directory=/opt/user/platform/gen
command=bash /opt/user/platform/gen/ui_starter.sh

[program:desktop-setup]
priority=805
directory=/opt/user/platform/gen
command=/bin/bash -c "/opt/user/platform/gen/setup_desktop.sh && exec sleep infinity"
autostart=true
autorestart=false
startsecs=0
