import iip.Registry
from iip.Version import Version
from iip.Service import ServiceState
from iip.Service import ServiceKind
from datatypes.NewInput import NewInput
from datatypes.NewOutput import NewOutput
from interfaces.PyServiceInterface import PyServiceInterface

class PyService(PyServiceInterface):
    """Template service implementation for PyService
       Generated by: EASy-Producer."""
    
    def __init__(self):
        """Initializes the service.""" 
        super().__init__()
    
    def processNewInput(self, data: NewInput):
        """Asynchronous data processing method. Use self.ingest(data) to pass the result back to the data stream.
    
        Parameters:
          - data -- the data to process
        """
        #create result instance and call self.ingest(data)
        raise NotImplementedError

#registers itself
PyService()
