from interfaces.KodexPythonServiceInterface import KodexPythonServiceInterface
from datatypes.Rec13Anon import Rec13Anon

class KodexPythonService(KodexPythonServiceInterface):
    """Service implementation for PythonService based on provided parts, in particular registration of methods
       with service environment. Just the global constructor execution is needed - will be loaded automatically
       and identified through ID in generated code.
       Generated by: EASy-Producer."""
       
    def __init__(self):
        """Initializes the service.""" 
        super().__init__()
        
    def processRec13Anon(self, data: Rec13Anon):
        """Asynchronous data processing method for Rec13Anon. 
    
        Parameters:
          - data -- the data to process
        """
        # we could do magic here, but we just "return" the unmodified data asynchronously
        self.ingest(data)
       
KodexPythonService()