package de.oktoflow.platform.examples.mdzh;

import java.io.*;        
import de.iip_ecosphere.platform.services.environment.*;
import iip.datatypes.*;
import iip.impl.*;

/**
 * Service implementation for net node 'PcfService'.
 * Generated by: EASy-Producer.
 */
public class PcfService extends PcfServiceImpl {

    /**
    * Fallback constructor, also used for testing main program.
    */
    public PcfService() {
        super(ServiceKind.TRANSFORMATION_SERVICE);
    }

    /**
    * Creates a service instance from a service id and a YAML artifact.
    * 
    * @param serviceId the service id
    * @param ymlFile the YML file containing the YAML artifact with the service descriptor
    */
    public PcfService(String serviceId, InputStream ymlFile) {
        super(serviceId, ymlFile);
    }

    @Override
    public void processLaserOutput(LaserOutput data) {
        // TODO call ingest<Type>(instance). Possible output types: PcfOutputImpl
    }
    @Override
    public void processPcfAasOutput(PcfAasOutput data) {
        // TODO call ingest<Type>(instance). Possible output types: PcfOutputImpl
    }
                
    
}
