name: Publish docker images

on:
  push:
    tags:
      - v*.*.*

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Extract version
        run: echo VERSION=${GITHUB_REF#refs/*/} >> $GITHUB_ENV
      - name: Check output
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          echo $VERSION
          echo ${{ env.VERSION }}
      - name: Build and push platform
        uses: docker/build-push-action@v1
        with:
          build_args: VERSION=${{ env.VERSION }}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PW }}        
          repository: inoeg/eps
          tag_with_ref: true
          dockerfile: ./platform/tools/install/container/fullPlatform/platform/Dockerfile
      - name: Build and push cli
        uses: docker/build-push-action@v1
        with:
          build_args: VERSION=${{ env.VERSION }}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PW }}        
          repository: inoeg/sd
          tag_with_ref: true
          dockerfile: ./platform/tools/install/container/fullPlatform/cli/Dockerfile
