name: Publish docker images

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Extract version
        run: echo VERSION=${GITHUB_REF#refs/*/} >> $GITHUB_ENV
      - name: Check output
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          echo $VERSION
          echo ${{ env.VERSION }}
          ls
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Install the platform basics
        run: |
          cd ./platform/tools/Install/platformDependencies
          mvn --batch-mode --update-snapshots install
          cd ../broker
          mvn --batch-mode --update-snapshots package
          cd ..
          mvn --batch-mode --update-snapshots package -DskipTests
      - name: Build the test app through tests
        run: |
          cd ./platform/configuration/configuration
          mvn --batch-mode --update-snapshots package
          cd ../../..
      - name: Instantiate the platform, prepare container building
        run: |
          cd ./platform/tools/Install
          sed -i 's/String serverHost = "147.172.178.145";/String serverHost = "172.19.0.22";/' src/main/easy/InstallTest.ivml
          echo "Using configuration:"
          cat src/main/easy/InstallTest.ivml
          mvn --batch-mode --update-snapshots exec:java -Dexec.args="InstallTest src/main/easy gen"
          cp container/fullPlatform/platform/*.sh gen
          cp broker/amqp.sh gen
          cp -r broker/brokerJars gen
          cp -r broker/src gen
          cp ../../configuration/configuration/gen/tests/SimpleMesh/SimpleMeshTestingApp/target/SimpleMeshTestingApp-0.1.0-SNAPSHOT.jar gen
          echo "Base directory for container creation:"
          ls gen
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PW }}        
      - name: Build and push platform
        uses: docker/build-push-action@v2
        with:
          build-args: VERSION=${{ env.VERSION }}
          push: true
          tags: iipecosphere/platform:platform_all.latest
          context: ./platform/tools/Install/gen/
          file: ./platform/tools/Install/container/fullPlatform/platform/Dockerfile
      - name: Build and push cli
        uses: docker/build-push-action@v2
        with:
          build-args: VERSION=${{ env.VERSION }}
          push: true
          tags: iipecosphere/platform:cli.latest
          context: ./platform/tools/Install/gen/
          file: ./platform/tools/Install/container/fullPlatform/cli/Dockerfile
