name: Publish docker images

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Extract version
        run: echo VERSION=${GITHUB_REF#refs/*/} >> $GITHUB_ENV
      - name: Check output
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          echo $VERSION
          echo ${{ env.VERSION }}
          ls
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Instantiate the platform
        run: |
          cd ./platform/tools/Install/platformDependencies
          mvn --batch-mode --update-snapshots install
          cd ../broker
          mvn --batch-mode --update-snapshots package
          cd ..
          mvn --batch-mode --update-snapshots package -DskipTests
          sed -i 's/String serverHost = "147.172.178.145";/String serverHost = "172.19.0.22";/' src/main/easy/InstallTest.ivml
          echo "Using configuration:"
          cat src/main/easy/InstallTest.ivml
          mvn --batch-mode --update-snapshots exec:java -Dexec.args="InstallTest src/main/easy gen"
          cp container/fullPlatform/platform/*.sh gen
          echo "Base directory for container creation:"
          ls gen
      - name: Build and push platform
        uses: docker/build-push-action@v1
        with:
          build_args: VERSION=${{ env.VERSION }}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PW }}        
          repository: iipecosphere/platform
          tag_with_ref: true
          context: ./platform/tools/Install/gen/
          dockerfile: ./platform/tools/Install/container/fullPlatform/platform/Dockerfile
      - name: Build and push cli
        uses: docker/build-push-action@v1
        with:
          build_args: VERSION=${{ env.VERSION }}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PW }}        
          repository: iipecosphere/platform
          tag_with_ref: true
          context: ./platform/tools/Install/gen/
          dockerfile: ./platform/tools/Install/container/fullPlatform/cli/Dockerfile
